artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  data_url: https://drive.google.com/file/d/1ZPNgpkIGYPoUToUy4-xSDKjnLxuGo566/view?usp=drive_link  ## Add url to respective directory
  data_file: artifacts/data_ingestion/raw_data.csv



data_validation:
  root_dir: artifacts/data_validation
  status: artifacts/data_validation/status.txt
  data_file: artifacts/data_ingestion/clean_data.csv


data_transformation:
  root_dir: artifacts/data_transformation
  train_data: artifacts/data_transformation/train_data.csv
  test_data: artifacts/data_transformation/test_data.csv
  trans_obj: artifacts/data_transformation/transform_data.pkl
  data_file: artifacts/data_ingestion/clean_data.csv



model_training:
  root_dir: artifacts/model_training
  train_data: artifacts/data_transformation/train_data.csv
  test_data: artifacts/data_transformation/test_data.csv
  metrics: artifacts/model_training/metrics.json
  trans_obj: artifacts/data_transformation/transform_data.pkl
  

